apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: account-service
  namespace: order-system-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: account-service
        version: v1
    spec:
      securityContext:
        readOnlyRootFilesystem: true
      containers:
      - name: account-service
        image: yoshio.azurecr.io/tyoshio2002/account-service:1.30
        terminationGracePeriodSeconds: 60
        livenessProbe:
          httpGet:
            path: /app/account/rest/hello
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /app/account/rest/hello
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
  name: account-service
  namespace: order-system-production
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  - port: 443
    name: https
    targetPort: 8080
  selector:
    app: account-service
  sessionAffinity: None
  type: ClusterIP
