apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: order-system-production
data:
  ACCOUT_SERVICE_SERVER_URL: "account-service.order-system-production.svc.cluster.local"

