apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  namespace: order-system-production
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: account-service
          servicePort: 80
