apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: payara-egress-rule
spec:
  destination:
    service: www.payara.fish
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: hazelcast-egress-rule
spec:
  destination:
    service: phonehome.hazelcast.com
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
