apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: account-service-route
  namespace: order-system-production
spec:
  destination:
    name: account-service
    namespace: order-system-production
    domain: svc.cluster.local
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
